### ISSUE TITLE
go mod tidy: go.mod file indicates go 1.17, but maximum supported version is 1.15

### ISSUE THREAD

**Issue by tjyang** [hupe1980/scan4log4shell#3]
Look like this project only work with go-1.17 while  default go  rpm on centos 7 is only 1.15.

-  Still don't know how to fix this compilation error after reading R1.

```
[pi@centos7t01 scan4log4shell]$rpm -qa |grep golang
golang-1.15.14-1.el7.x86_64
golang-bin-1.15.14-1.el7.x86_64
golang-src-1.15.14-1.el7.noarch
[pi@va32centos7t01 scan4log4shell]$ cat /etc/redhat-release
CentOS Linux release 7.9.2009 (Core)
[pi@centos7t01 scan4log4shell]$ make setup
go mod tidy: go.mod file indicates go 1.17, but maximum supported version is 1.15
make: *** [setup] Error 1
[pi@centos7t01 scan4log4shell]$

```
R1: https://github.com/asim/go-micro/issues/2367

**Comment by tjyang** [comment]
Anyway you can support building this tool using golang-1.16 ? 

- RL8.5  only have version up to 1.16 from appstream.
```
[me@rocky8t01 scan4log4shell]$ cat /etc/redhat-release
Rocky Linux release 8.5 (Green Obsidian)
[me@rocky8t01 scan4log4shell]$

[me@rocky8t01 scan4log4shell]$ sudo dnf install golang
timescale_timescaledb                                                                          163  B/s | 833  B     00:05
Dependencies resolved.
===============================================================================================================================
 Package                        Architecture      Version                                           Repository            Size
===============================================================================================================================
Installing:
 golang                         x86_64            1.16.12-1.module+el8.5.0+720+c057d5cf             appstream            687 k
Installing dependencies:
 golang-bin                     x86_64            1.16.12-1.module+el8.5.0+720+c057d5cf             appstream             92 M
 golang-src                     noarch            1.16.12-1.module+el8.5.0+720+c057d5cf             appstream            8.2 M
 keyutils-libs-devel            x86_64            1.5.10-9.el8                                      baseos                47 k

```

**Comment by tjyang** [comment]
- changing version in go.mod file seems fix the issue and I was able to get a binary.
```
[me@rocky8t01 scan4log4shell]$ git diff go.mod
diff --git a/go.mod b/go.mod
index 0c41a3a..237e695 100644
--- a/go.mod
+++ b/go.mod
@@ -1,81 +1,17 @@
 module github.com/hupe1980/log4shellscan

-go 1.17
+go 1.16
```
